project:
  type: website
  output-dir: docs

website:
  title: "Leilanie Rubinstein"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - photography.qmd

format:
  html:
    theme: 
      light: morph
      dark: solar
    css: styles.css
    toc: true
    page-layout: full



