project:
  type: website
  output-dir: docs

website:
  title: "Leilanie Rubinstein"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - grads.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

output:
  quarto::bookdown_html:
    css: styles.css

editor: visual
  
  
  