---
title: "About Me"
---

### Biography

I earned my Bachelor of Arts in Political Science and Environmental Studies from the University of California, Santa Barbara in 2021. Inspired by Santa Barbara's legacy of environmental activism, I have dedicated myself to running local and federal campaigns with social justice and conservation-driven values for the past seven years. Following my undergraduate degree, I worked at an environmental law firm, specializing in litigation and regulatory disputes relating to remediation of Superfund sites. My professional experience includes roles in political organizing, legislation, and environmental law, where I honed skills in data management, community engagement, and environmental policy analysis.

Currently pursuing a Master of Environmental Data Science at the Bren School, I aspire to work in government or to conduct policy relevant research after graduation. I aim to leverage data science techniques to develop solutions for resource management and climate change mitigation, promoting sustainable practices and enhancing climate resilience locally and globally.

In my free time, I enjoy mountain biking, gaming, and exploring nature and the night sky through my camera lens.



<!-- ## What I do for work -->

<!-- <p class="spacecadet-text center-text">some text</p> -->

<!-- ## What I do for fun -->

<!-- <p class="center-spacecadet">give the people what they want!</p> -->

<!-- here is some more text [.center-spacecadet] -->

<!-- ::: {.spacecadet-text} -->
<!-- here is a line -->

<!-- here is another line -->
<!-- ::: -->